apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /srv/nfs/jenkins
    server: support1.754d.internal
  persistentVolumeReclaimPolicy: Retain