apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "test-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "100m" 
        memory: "750Mi" 
      min:
        cpu: "10m" 
        memory: "5Mi" 
    - type: "Container"
      max:
        cpu: "100m"
        memory: "750Mi" 
      min:
        cpu: "10m" 
        memory: "5Mi" 
      default:
        cpu: "50m" 
        memory: "100Mi" 
