- name: Setup
  hosts: masters
  tasks:
    - name: Adding Service Affinity configuration for "Dedicated node for each Client" clause
      replace:
        path: /etc/origin/master/scheduler.json
        regexp: '"region"'
        replace: '"region", "client"'
    - name: Setting admissionControl for "admissionControl plugin sets specific limits per label (client/customer)" clause
      blockinfile:
        path: /etc/origin/master/master-config.yaml
        marker: "# ANSIBLE MANAGED BLOCK"
        insertafter: "  pluginConfig:"
        content: |2
              ProjectRequestLimit:
                configuration:
                  apiVersion: v1
                  kind: ProjectRequestLimitConfig
                  limits:
                  - selector:
                      level: admin
                  - selector:
                      level: advanced
                    maxProjects: 10
                  - maxProjects: 2
    - name: Setting project template for "The new project template is modified so that it includes a LimitRange" clause
      replace:
        path: /etc/origin/master/master-config.yaml
        regexp: "projectRequestTemplate: ''"
        replace: "projectRequestTemplate: 'default/my-project-request'"